# dbt_project.yml

name: 'snowflake_dbt'
version: '1.0.0'

# DBT profile used to connect to your data warehouse
profile: 'snowflake_dbt'

# Define global variables for the project
vars:
  # Used in schema.yml for appending suffix to database in test environment
  db_suffix: '_Test'

# DBT project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean these folders on `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model-level configurations
models:
  snowflake_dbt:
    # Apply config to all models in this project namespace
    +database: "{{ target.database }}"
