# This file is used to define the schema tables/views for the transformed layer in dbt/snowflake.
# It includes the sources from which the data is derived, along with their descriptions.

version: 2

sources:
  - name: clean_layer_realized_savings_clean_not_ignored
    description: "source database for getting realized savings data"
    database: clean_layer
    schema: public
    tables:
      - name: realized_savings_report_clean_not_ignored
        description: "View containing realized savings data with employee information"
  - name: staging_layer_current_customers_without_demo_accounts
    description: "source database for getting customer data without demo accounts"
    database: staging_layer
    schema: mastermgmt
    tables:
      - name: client_master_current_customers_without_demo_accounts
        description: "View containing customer data without demo accounts"
  - name: raw_layer_saverx_employee
    description: "source database for getting employee data"
    database: raw_layer
    schema: public
    tables:
      - name: saverx_employee
        description: "View containing employee data"
  - name: staging_layer_master_drug
    description: "source database for getting master drug data"
    database: staging_layer
    schema: master
    tables:
      - name: vw_master_drug
        description: "View containing master drug data"
  - name: raw_layer_patient_condition
    description: "source database for getting patient condition data"
    database: raw_layer
    schema: master
    tables:
      - name: master_patientmedicalcondition
        description: "View containing patient condition data"
  - name: raw_layer_saverx_plan
    description: "source database for getting SaverX plan data"
    database: raw_layer
    schema: public
    tables:
      - name: saverx_plan
        description: "View containing SaverX plan data"
  - name: raw_layer_client_childcompany
    description: "source database for getting client child company data"
    database: raw_layer
    schema: public
    tables:
      - name: client_childcompany
        description: "View containing client child company data"
  - name: raw_layer_saverx_pbmhistory
    description: "source database for getting SaverX PBM history data"
    database: raw_layer
    schema: public
    tables:
      - name: saverx_pbmhistory
        description: "View containing SaverX PBM history data"